apiVersion: v1
kind: Service
metadata:
  name: bq-json-svc
  labels:
    tier: backend
spec:
  ports:
  - port: 9001
    protocol: TCP
    name: http
  selector:
    app: bq-json-svc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bq-json-svc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bq-json-svc
        tier: backend
    spec:
      containers:
      - name: bq-json-svc
        image: eu.gcr.io/{project_id}/{image_name}:{version_tag}
        ports:
        - containerPort: 9001
